zip core_sprites.zip \
addcontent.png \
check.gif \
check_on.gif \
close.gif \
closedarrow.png \
collapseAll.png \
compare-addition.gif \
compare-removal.gif \
copy-folder.png \
delete.gif \
edit.gif \
error.png \
expandAll.png \
favorite.png \
file.gif \
file_model.gif \
folder.gif \
gear.png \
go-up.png \
hamburger.png \
information.png \
leftarrow.png \
link.png \
list.png \
menu_twistie.gif \
move_down.gif \
move_up.gif \
none.png \
ok.gif \
openarrow.png \
godev-logo.png \
outline.png \
refresh.png \
replaceAll.gif \
rightarrow.png \
sep.gif \
silhouette.png \
start.gif \
stop.gif \
stylesheet.gif \
thumbnail.png \
warning.gif \
wrench.png
