#!/bin/sh
zip core_sprites.zip \
addcontent.png \
check.gif \
check_on.gif \
close.gif \
closedarrow.png \
collapseAll.png \
compare-addition.gif \
compare-removal.gif \
copy-folder.png \
delete.png \
downarrow.gif \
edit.png \
error.png \
expandAll.png \
file.png \
file_model.gif \
folder.png \
gear.png \
go-down.png \
go-up.png \
hamburger.png \
information.png \
initproject.png \
leftarrow.png \
link.png \
list.png \
move-down.png \
move-up.png \
none.png \
ok.gif \
openarrow.png \
orion-logo.png \
outline.png \
refresh.png \
replaceAll.gif \
rightarrow.png \
sep.gif \
silhouette.png \
start.gif \
stop.gif \
thumbnail.png \
warning.gif \
wrench.png
